Removed trove classifiers from setup.py.
Something has changed that caused the upload to fail:

Submitting dist/mido-1.1.20.tar.gz to https://upload.pypi.org/legacy/
Upload failed (400): classifiers: 'FieldStorage('classifiers', 'Development Status :: 5 - Production/Stable')' is not a valid choice for this field
error: Upload failed (400): classifiers: 'FieldStorage('classifiers', 'Development Status :: 5 - Production/Stable')' is not a valid choice for this field

The only solution I could find was to remove the classifiers.